# fly.toml file generated for leetcode-bot on 2023-03-26T22:11:49+08:00

app = "leetcode-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[build]
  dockerfile = "Dockerfile"

[env]

[experimental]
  auto_rollback = true

[processes]
  cron_job = "yacron -c /app/crontab.yml"

[[services]]
  processes = ["cron_job"]