[tool.poetry]
name = "leetcode-bot"
version = "0.1.0"
description = ""
authors = ["Niccolo Dejito <ncdejito@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.6"
zulip = "^0.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
